name: Schedule Test No BOM

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "9,24,39,54 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "UTC time:"
          date -u